external_integration_mappings: []
python: '3.11'
secret_mappings: []
variables:
  - name: sfdc_account
    type: text
    value: snoweaver-dev-ed.develop
  - name: test_var
    type: text
    value: test
