
name: Deploy

on:
  workflow_call:
    inputs:
      SNOWSQL_CONFIG:
        required: true
        type: string
    secrets:
      SNFLK_PRIVATE_KEY_PASSPHRASE:
        required: true
      SNFLK_PRIVATE_KEY:
        required: true


jobs:

  deploy:

    runs-on: ubuntu-latest

    env:
      SNOWSQL_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNFLK_PRIVATE_KEY_PASSPHRASE }}

    steps:

      - uses: actions/checkout@v4
     
      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.3/linux_x86_64/snowsql-1.3.1-linux_x86_64.bash
          SNOWSQL_DEST=~/.local/bin/ SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.3.1-linux_x86_64.bash
          echo -e "${{ secrets.SNFLK_PRIVATE_KEY }}" > ~/rsa_key.p8
          echo -e "${{ inputs.SNOWSQL_CONFIG }}" > ~/.snowsql/config

      - name: Install Snoweaver CLI
        run: |
          curl -o ~/.local/bin/sw https://raw.githubusercontent.com/Snoweaver-Labs/quickstart/main/cli/sw
          chmod 700 ~/.local/bin/sw

      - name: Upload resource files to CODE
        run: |
          sw put all -d

      - name: Import resources
        run: |
          sw import all -d

      - name: Compile all the jobs
        run: |
          sw build all